version: 2
jobs:
   build:
     docker:
       - image: reznik/gnat:wasm
     steps:
       - checkout
       - run: gprbuild -p -P gnat/garlic.gpr
       - run: gprbuild -p -P gnat/gnatdist.gpr
       - run: gprinstall -p -P gnat/garlic.gpr --prefix=/tmp/garlic --sources-subdir=lib/garlic
       - run: gprinstall -p -P gnat/gnatdist.gpr --prefix=/tmp/garlic
       - run: Tests/run.sh /tmp/garlic
