version: 2
jobs:
   build:
     docker:
       - image: reznik/gnat:wasm
     steps:
       - checkout
       - run: sh ./configure --prefix=/tmp/garlic
       - run: make all install GNATFLAGS="-O2 -gnatpn -gnatwu -gnatwn -gnatyI"
       - run: Tests/run.sh /tmp/garlic
