version: 2
jobs:
   build:
     docker:
       - image: reznik/garlic
     steps:
       - checkout
       - run: microdnf install adawebpack
       - run:
          command: chromedriver --verbose
          background: true
       - run: . /etc/profile.d/gnat-project.sh; make check
